### PR TITLE
Update README.md and create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by pavankuppa1**

### CODE REVIEW

**Comment by pavankuppa1** [comment]
@sabzo This is the PR.Thank you.

**Review by sabzo — APPROVED** [review]
Awesome

**Comment by pavankuppa1** [comment]
Thank you sir.But it is not merged into the master branch.When will it
merge sir..

**Review by sabzo — CHANGES_REQUESTED** [review]
I have created a `develop` branch which can serve as the base for proposed changes. I would rather keep `master` branch only for releases. 

This project also needs automated tests: unit tests in addition to end-to-end testing.

**Comment by pavankuppa1** [comment]
Ok sir.Thank you.

**Comment by pavankuppa1** [comment]
Sir check the new PR to the develop branch sir.Thank you. PR #35

**Pull request closed without merging**
